[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
signer_authorization = "FeKh59XMh6BcN6UdekHnaFHsNH9NVE121GgDzSyYPKKS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -r tsx -p ./tsconfig.json -t 1000000 tests/**/*.ts"
